### ISSUE TITLE
Changes for v1.46e not found in repo

### ISSUE THREAD

**Issue by muzimuzhi** [texno3/spbmark#1]
I noticed the release of `spbmark` v1.46d (2024-02-16) on CTAN (see [CTAN announcement](https://ctan.org/ctan-ann/id/mailman.6484.1707931919.3764.ctan-ann@ctan.org) for v1.46e (2024-02-13)), but currently the latest commit in this repository was 06a7ff8 (version 1.4, 2022-05-06).

**Comment by texno3** [comment]
> I noticed the release of `spbmark` v1.46d (2024-02-16) on CTAN (see [CTAN announcement](https://ctan.org/ctan-ann/id/mailman.6484.1707931919.3764.ctan-ann@ctan.org) for v1.46e (2024-02-13)), but currently the latest commit in this repository was [06a7ff8](https://github.com/texno3/spbmark/commit/06a7ff89744daa475bf1857d1ef81a42ffd0c134) (version 1.4, 2022-05-06).

I haven't paid attention to this repository for a longer period of time and have now updated to the new version.

**Comment by muzimuzhi** [comment]
thanks
